//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace STraF_U {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DatasetLoan : DataSet {
        
        private LoanDataTable tableLoan;
        
        private LoanTuitionDataTable tableLoanTuition;
        
        private DataRelation relationLoanLoanTuition;
        
        public DatasetLoan() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DatasetLoan(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Loan"] != null)) {
                    this.Tables.Add(new LoanDataTable(ds.Tables["Loan"]));
                }
                if ((ds.Tables["LoanTuition"] != null)) {
                    this.Tables.Add(new LoanTuitionDataTable(ds.Tables["LoanTuition"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public LoanDataTable Loan {
            get {
                return this.tableLoan;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public LoanTuitionDataTable LoanTuition {
            get {
                return this.tableLoanTuition;
            }
        }
        
        public override DataSet Clone() {
            DatasetLoan cln = ((DatasetLoan)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Loan"] != null)) {
                this.Tables.Add(new LoanDataTable(ds.Tables["Loan"]));
            }
            if ((ds.Tables["LoanTuition"] != null)) {
                this.Tables.Add(new LoanTuitionDataTable(ds.Tables["LoanTuition"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableLoan = ((LoanDataTable)(this.Tables["Loan"]));
            if ((this.tableLoan != null)) {
                this.tableLoan.InitVars();
            }
            this.tableLoanTuition = ((LoanTuitionDataTable)(this.Tables["LoanTuition"]));
            if ((this.tableLoanTuition != null)) {
                this.tableLoanTuition.InitVars();
            }
            this.relationLoanLoanTuition = this.Relations["LoanLoanTuition"];
        }
        
        private void InitClass() {
            this.DataSetName = "DatasetLoan";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DatasetLoan.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableLoan = new LoanDataTable();
            this.Tables.Add(this.tableLoan);
            this.tableLoanTuition = new LoanTuitionDataTable();
            this.Tables.Add(this.tableLoanTuition);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("LoanLoanTuition", new DataColumn[] {
                        this.tableLoan.idColumn}, new DataColumn[] {
                        this.tableLoanTuition.stidColumn});
            this.tableLoanTuition.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            this.relationLoanLoanTuition = new DataRelation("LoanLoanTuition", new DataColumn[] {
                        this.tableLoan.idColumn}, new DataColumn[] {
                        this.tableLoanTuition.stidColumn}, false);
            this.Relations.Add(this.relationLoanLoanTuition);
        }
        
        private bool ShouldSerializeLoan() {
            return false;
        }
        
        private bool ShouldSerializeLoanTuition() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void LoanRowChangeEventHandler(object sender, LoanRowChangeEvent e);
        
        public delegate void LoanTuitionRowChangeEventHandler(object sender, LoanTuitionRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class LoanDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnid;
            
            private DataColumn columnlname;
            
            private DataColumn columnfname;
            
            private DataColumn columngender;
            
            private DataColumn columnprof;
            
            private DataColumn columngrade;
            
            private DataColumn columngpa;
            
            private DataColumn columnregion;
            
            private DataColumn columnadmisno;
            
            private DataColumn columnpasno;
            
            private DataColumn columnregno;
            
            private DataColumn columnfamily;
            
            private DataColumn columnincome;
            
            private DataColumn columnstate;
            
            private DataColumn columnnote;
            
            internal LoanDataTable() : 
                    base("Loan") {
                this.InitClass();
            }
            
            internal LoanDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            internal DataColumn lnameColumn {
                get {
                    return this.columnlname;
                }
            }
            
            internal DataColumn fnameColumn {
                get {
                    return this.columnfname;
                }
            }
            
            internal DataColumn genderColumn {
                get {
                    return this.columngender;
                }
            }
            
            internal DataColumn profColumn {
                get {
                    return this.columnprof;
                }
            }
            
            internal DataColumn gradeColumn {
                get {
                    return this.columngrade;
                }
            }
            
            internal DataColumn gpaColumn {
                get {
                    return this.columngpa;
                }
            }
            
            internal DataColumn regionColumn {
                get {
                    return this.columnregion;
                }
            }
            
            internal DataColumn admisnoColumn {
                get {
                    return this.columnadmisno;
                }
            }
            
            internal DataColumn pasnoColumn {
                get {
                    return this.columnpasno;
                }
            }
            
            internal DataColumn regnoColumn {
                get {
                    return this.columnregno;
                }
            }
            
            internal DataColumn familyColumn {
                get {
                    return this.columnfamily;
                }
            }
            
            internal DataColumn incomeColumn {
                get {
                    return this.columnincome;
                }
            }
            
            internal DataColumn stateColumn {
                get {
                    return this.columnstate;
                }
            }
            
            internal DataColumn noteColumn {
                get {
                    return this.columnnote;
                }
            }
            
            public LoanRow this[int index] {
                get {
                    return ((LoanRow)(this.Rows[index]));
                }
            }
            
            public event LoanRowChangeEventHandler LoanRowChanged;
            
            public event LoanRowChangeEventHandler LoanRowChanging;
            
            public event LoanRowChangeEventHandler LoanRowDeleted;
            
            public event LoanRowChangeEventHandler LoanRowDeleting;
            
            public void AddLoanRow(LoanRow row) {
                this.Rows.Add(row);
            }
            
            public LoanRow AddLoanRow(string lname, string fname, string gender, string prof, System.Byte grade, System.Single gpa, string region, string admisno, string pasno, string regno, System.Byte family, System.Single income, System.Byte state, string note) {
                LoanRow rowLoanRow = ((LoanRow)(this.NewRow()));
                rowLoanRow.ItemArray = new object[] {
                        null,
                        lname,
                        fname,
                        gender,
                        prof,
                        grade,
                        gpa,
                        region,
                        admisno,
                        pasno,
                        regno,
                        family,
                        income,
                        state,
                        note};
                this.Rows.Add(rowLoanRow);
                return rowLoanRow;
            }
            
            public LoanRow FindByid(int id) {
                return ((LoanRow)(this.Rows.Find(new object[] {
                            id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                LoanDataTable cln = ((LoanDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new LoanDataTable();
            }
            
            internal void InitVars() {
                this.columnid = this.Columns["id"];
                this.columnlname = this.Columns["lname"];
                this.columnfname = this.Columns["fname"];
                this.columngender = this.Columns["gender"];
                this.columnprof = this.Columns["prof"];
                this.columngrade = this.Columns["grade"];
                this.columngpa = this.Columns["gpa"];
                this.columnregion = this.Columns["region"];
                this.columnadmisno = this.Columns["admisno"];
                this.columnpasno = this.Columns["pasno"];
                this.columnregno = this.Columns["regno"];
                this.columnfamily = this.Columns["family"];
                this.columnincome = this.Columns["income"];
                this.columnstate = this.Columns["state"];
                this.columnnote = this.Columns["note"];
            }
            
            private void InitClass() {
                this.columnid = new DataColumn("id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnid);
                this.columnlname = new DataColumn("lname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlname);
                this.columnfname = new DataColumn("fname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnfname);
                this.columngender = new DataColumn("gender", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngender);
                this.columnprof = new DataColumn("prof", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnprof);
                this.columngrade = new DataColumn("grade", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngrade);
                this.columngpa = new DataColumn("gpa", typeof(System.Single), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngpa);
                this.columnregion = new DataColumn("region", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnregion);
                this.columnadmisno = new DataColumn("admisno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnadmisno);
                this.columnpasno = new DataColumn("pasno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpasno);
                this.columnregno = new DataColumn("regno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnregno);
                this.columnfamily = new DataColumn("family", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnfamily);
                this.columnincome = new DataColumn("income", typeof(System.Single), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnincome);
                this.columnstate = new DataColumn("state", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstate);
                this.columnnote = new DataColumn("note", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnote);
                this.Constraints.Add(new UniqueConstraint("DatasetLoanKey1", new DataColumn[] {
                                this.columnid}, true));
                this.columnid.AutoIncrement = true;
                this.columnid.AllowDBNull = false;
                this.columnid.Unique = true;
                this.columngender.DefaultValue = "эр";
                this.columngrade.DefaultValue = 1;
                this.columngpa.DefaultValue = 0F;
                this.columnregion.DefaultValue = "Улаанбаатар";
                this.columnfamily.DefaultValue = 1;
                this.columnincome.DefaultValue = 0F;
                this.columnstate.DefaultValue = 1;
            }
            
            public LoanRow NewLoanRow() {
                return ((LoanRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new LoanRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(LoanRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.LoanRowChanged != null)) {
                    this.LoanRowChanged(this, new LoanRowChangeEvent(((LoanRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.LoanRowChanging != null)) {
                    this.LoanRowChanging(this, new LoanRowChangeEvent(((LoanRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.LoanRowDeleted != null)) {
                    this.LoanRowDeleted(this, new LoanRowChangeEvent(((LoanRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.LoanRowDeleting != null)) {
                    this.LoanRowDeleting(this, new LoanRowChangeEvent(((LoanRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveLoanRow(LoanRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class LoanRow : DataRow {
            
            private LoanDataTable tableLoan;
            
            internal LoanRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableLoan = ((LoanDataTable)(this.Table));
            }
            
            public int id {
                get {
                    return ((int)(this[this.tableLoan.idColumn]));
                }
                set {
                    this[this.tableLoan.idColumn] = value;
                }
            }
            
            public string lname {
                get {
                    try {
                        return ((string)(this[this.tableLoan.lnameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.lnameColumn] = value;
                }
            }
            
            public string fname {
                get {
                    try {
                        return ((string)(this[this.tableLoan.fnameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.fnameColumn] = value;
                }
            }
            
            public string gender {
                get {
                    try {
                        return ((string)(this[this.tableLoan.genderColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.genderColumn] = value;
                }
            }
            
            public string prof {
                get {
                    try {
                        return ((string)(this[this.tableLoan.profColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.profColumn] = value;
                }
            }
            
            public System.Byte grade {
                get {
                    try {
                        return ((System.Byte)(this[this.tableLoan.gradeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.gradeColumn] = value;
                }
            }
            
            public System.Single gpa {
                get {
                    try {
                        return ((System.Single)(this[this.tableLoan.gpaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.gpaColumn] = value;
                }
            }
            
            public string region {
                get {
                    try {
                        return ((string)(this[this.tableLoan.regionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.regionColumn] = value;
                }
            }
            
            public string admisno {
                get {
                    try {
                        return ((string)(this[this.tableLoan.admisnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.admisnoColumn] = value;
                }
            }
            
            public string pasno {
                get {
                    try {
                        return ((string)(this[this.tableLoan.pasnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.pasnoColumn] = value;
                }
            }
            
            public string regno {
                get {
                    try {
                        return ((string)(this[this.tableLoan.regnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.regnoColumn] = value;
                }
            }
            
            public System.Byte family {
                get {
                    try {
                        return ((System.Byte)(this[this.tableLoan.familyColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.familyColumn] = value;
                }
            }
            
            public System.Single income {
                get {
                    try {
                        return ((System.Single)(this[this.tableLoan.incomeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.incomeColumn] = value;
                }
            }
            
            public System.Byte state {
                get {
                    try {
                        return ((System.Byte)(this[this.tableLoan.stateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.stateColumn] = value;
                }
            }
            
            public string note {
                get {
                    try {
                        return ((string)(this[this.tableLoan.noteColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoan.noteColumn] = value;
                }
            }
            
            public bool IslnameNull() {
                return this.IsNull(this.tableLoan.lnameColumn);
            }
            
            public void SetlnameNull() {
                this[this.tableLoan.lnameColumn] = System.Convert.DBNull;
            }
            
            public bool IsfnameNull() {
                return this.IsNull(this.tableLoan.fnameColumn);
            }
            
            public void SetfnameNull() {
                this[this.tableLoan.fnameColumn] = System.Convert.DBNull;
            }
            
            public bool IsgenderNull() {
                return this.IsNull(this.tableLoan.genderColumn);
            }
            
            public void SetgenderNull() {
                this[this.tableLoan.genderColumn] = System.Convert.DBNull;
            }
            
            public bool IsprofNull() {
                return this.IsNull(this.tableLoan.profColumn);
            }
            
            public void SetprofNull() {
                this[this.tableLoan.profColumn] = System.Convert.DBNull;
            }
            
            public bool IsgradeNull() {
                return this.IsNull(this.tableLoan.gradeColumn);
            }
            
            public void SetgradeNull() {
                this[this.tableLoan.gradeColumn] = System.Convert.DBNull;
            }
            
            public bool IsgpaNull() {
                return this.IsNull(this.tableLoan.gpaColumn);
            }
            
            public void SetgpaNull() {
                this[this.tableLoan.gpaColumn] = System.Convert.DBNull;
            }
            
            public bool IsregionNull() {
                return this.IsNull(this.tableLoan.regionColumn);
            }
            
            public void SetregionNull() {
                this[this.tableLoan.regionColumn] = System.Convert.DBNull;
            }
            
            public bool IsadmisnoNull() {
                return this.IsNull(this.tableLoan.admisnoColumn);
            }
            
            public void SetadmisnoNull() {
                this[this.tableLoan.admisnoColumn] = System.Convert.DBNull;
            }
            
            public bool IspasnoNull() {
                return this.IsNull(this.tableLoan.pasnoColumn);
            }
            
            public void SetpasnoNull() {
                this[this.tableLoan.pasnoColumn] = System.Convert.DBNull;
            }
            
            public bool IsregnoNull() {
                return this.IsNull(this.tableLoan.regnoColumn);
            }
            
            public void SetregnoNull() {
                this[this.tableLoan.regnoColumn] = System.Convert.DBNull;
            }
            
            public bool IsfamilyNull() {
                return this.IsNull(this.tableLoan.familyColumn);
            }
            
            public void SetfamilyNull() {
                this[this.tableLoan.familyColumn] = System.Convert.DBNull;
            }
            
            public bool IsincomeNull() {
                return this.IsNull(this.tableLoan.incomeColumn);
            }
            
            public void SetincomeNull() {
                this[this.tableLoan.incomeColumn] = System.Convert.DBNull;
            }
            
            public bool IsstateNull() {
                return this.IsNull(this.tableLoan.stateColumn);
            }
            
            public void SetstateNull() {
                this[this.tableLoan.stateColumn] = System.Convert.DBNull;
            }
            
            public bool IsnoteNull() {
                return this.IsNull(this.tableLoan.noteColumn);
            }
            
            public void SetnoteNull() {
                this[this.tableLoan.noteColumn] = System.Convert.DBNull;
            }
            
            public LoanTuitionRow[] GetLoanTuitionRows() {
                return ((LoanTuitionRow[])(this.GetChildRows(this.Table.ChildRelations["LoanLoanTuition"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class LoanRowChangeEvent : EventArgs {
            
            private LoanRow eventRow;
            
            private DataRowAction eventAction;
            
            public LoanRowChangeEvent(LoanRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public LoanRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class LoanTuitionDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnstid;
            
            private DataColumn columntdate;
            
            private DataColumn columntsize;
            
            private DataColumn columntdesc;
            
            internal LoanTuitionDataTable() : 
                    base("LoanTuition") {
                this.InitClass();
            }
            
            internal LoanTuitionDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn stidColumn {
                get {
                    return this.columnstid;
                }
            }
            
            internal DataColumn tdateColumn {
                get {
                    return this.columntdate;
                }
            }
            
            internal DataColumn tsizeColumn {
                get {
                    return this.columntsize;
                }
            }
            
            internal DataColumn tdescColumn {
                get {
                    return this.columntdesc;
                }
            }
            
            public LoanTuitionRow this[int index] {
                get {
                    return ((LoanTuitionRow)(this.Rows[index]));
                }
            }
            
            public event LoanTuitionRowChangeEventHandler LoanTuitionRowChanged;
            
            public event LoanTuitionRowChangeEventHandler LoanTuitionRowChanging;
            
            public event LoanTuitionRowChangeEventHandler LoanTuitionRowDeleted;
            
            public event LoanTuitionRowChangeEventHandler LoanTuitionRowDeleting;
            
            public void AddLoanTuitionRow(LoanTuitionRow row) {
                this.Rows.Add(row);
            }
            
            public LoanTuitionRow AddLoanTuitionRow(LoanRow parentLoanRowByLoanLoanTuition, System.DateTime tdate, System.Single tsize, string tdesc) {
                LoanTuitionRow rowLoanTuitionRow = ((LoanTuitionRow)(this.NewRow()));
                rowLoanTuitionRow.ItemArray = new object[] {
                        parentLoanRowByLoanLoanTuition[0],
                        tdate,
                        tsize,
                        tdesc};
                this.Rows.Add(rowLoanTuitionRow);
                return rowLoanTuitionRow;
            }
            
            public LoanTuitionRow FindBystidtdate(int stid, System.DateTime tdate) {
                return ((LoanTuitionRow)(this.Rows.Find(new object[] {
                            stid,
                            tdate})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                LoanTuitionDataTable cln = ((LoanTuitionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new LoanTuitionDataTable();
            }
            
            internal void InitVars() {
                this.columnstid = this.Columns["stid"];
                this.columntdate = this.Columns["tdate"];
                this.columntsize = this.Columns["tsize"];
                this.columntdesc = this.Columns["tdesc"];
            }
            
            private void InitClass() {
                this.columnstid = new DataColumn("stid", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstid);
                this.columntdate = new DataColumn("tdate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntdate);
                this.columntsize = new DataColumn("tsize", typeof(System.Single), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntsize);
                this.columntdesc = new DataColumn("tdesc", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntdesc);
                this.Constraints.Add(new UniqueConstraint("DatasetLoanKey2", new DataColumn[] {
                                this.columnstid,
                                this.columntdate}, true));
                this.Constraints.Add(new UniqueConstraint("key1", new DataColumn[] {
                                this.columnstid}, false));
                this.columnstid.AllowDBNull = false;
                this.columnstid.Unique = true;
                this.columntdate.AllowDBNull = false;
            }
            
            public LoanTuitionRow NewLoanTuitionRow() {
                return ((LoanTuitionRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new LoanTuitionRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(LoanTuitionRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.LoanTuitionRowChanged != null)) {
                    this.LoanTuitionRowChanged(this, new LoanTuitionRowChangeEvent(((LoanTuitionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.LoanTuitionRowChanging != null)) {
                    this.LoanTuitionRowChanging(this, new LoanTuitionRowChangeEvent(((LoanTuitionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.LoanTuitionRowDeleted != null)) {
                    this.LoanTuitionRowDeleted(this, new LoanTuitionRowChangeEvent(((LoanTuitionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.LoanTuitionRowDeleting != null)) {
                    this.LoanTuitionRowDeleting(this, new LoanTuitionRowChangeEvent(((LoanTuitionRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveLoanTuitionRow(LoanTuitionRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class LoanTuitionRow : DataRow {
            
            private LoanTuitionDataTable tableLoanTuition;
            
            internal LoanTuitionRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableLoanTuition = ((LoanTuitionDataTable)(this.Table));
            }
            
            public int stid {
                get {
                    return ((int)(this[this.tableLoanTuition.stidColumn]));
                }
                set {
                    this[this.tableLoanTuition.stidColumn] = value;
                }
            }
            
            public System.DateTime tdate {
                get {
                    return ((System.DateTime)(this[this.tableLoanTuition.tdateColumn]));
                }
                set {
                    this[this.tableLoanTuition.tdateColumn] = value;
                }
            }
            
            public System.Single tsize {
                get {
                    try {
                        return ((System.Single)(this[this.tableLoanTuition.tsizeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoanTuition.tsizeColumn] = value;
                }
            }
            
            public string tdesc {
                get {
                    try {
                        return ((string)(this[this.tableLoanTuition.tdescColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableLoanTuition.tdescColumn] = value;
                }
            }
            
            public LoanRow LoanRow {
                get {
                    return ((LoanRow)(this.GetParentRow(this.Table.ParentRelations["LoanLoanTuition"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["LoanLoanTuition"]);
                }
            }
            
            public bool IstsizeNull() {
                return this.IsNull(this.tableLoanTuition.tsizeColumn);
            }
            
            public void SettsizeNull() {
                this[this.tableLoanTuition.tsizeColumn] = System.Convert.DBNull;
            }
            
            public bool IstdescNull() {
                return this.IsNull(this.tableLoanTuition.tdescColumn);
            }
            
            public void SettdescNull() {
                this[this.tableLoanTuition.tdescColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class LoanTuitionRowChangeEvent : EventArgs {
            
            private LoanTuitionRow eventRow;
            
            private DataRowAction eventAction;
            
            public LoanTuitionRowChangeEvent(LoanTuitionRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public LoanTuitionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
