//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace STraF_U {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DatasetHerder : DataSet {
        
        private HerderDataTable tableHerder;
        
        private HerderTuitionDataTable tableHerderTuition;
        
        private DataRelation relationHerderHerderTuition;
        
        public DatasetHerder() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DatasetHerder(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Herder"] != null)) {
                    this.Tables.Add(new HerderDataTable(ds.Tables["Herder"]));
                }
                if ((ds.Tables["HerderTuition"] != null)) {
                    this.Tables.Add(new HerderTuitionDataTable(ds.Tables["HerderTuition"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public HerderDataTable Herder {
            get {
                return this.tableHerder;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public HerderTuitionDataTable HerderTuition {
            get {
                return this.tableHerderTuition;
            }
        }
        
        public override DataSet Clone() {
            DatasetHerder cln = ((DatasetHerder)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Herder"] != null)) {
                this.Tables.Add(new HerderDataTable(ds.Tables["Herder"]));
            }
            if ((ds.Tables["HerderTuition"] != null)) {
                this.Tables.Add(new HerderTuitionDataTable(ds.Tables["HerderTuition"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableHerder = ((HerderDataTable)(this.Tables["Herder"]));
            if ((this.tableHerder != null)) {
                this.tableHerder.InitVars();
            }
            this.tableHerderTuition = ((HerderTuitionDataTable)(this.Tables["HerderTuition"]));
            if ((this.tableHerderTuition != null)) {
                this.tableHerderTuition.InitVars();
            }
            this.relationHerderHerderTuition = this.Relations["HerderHerderTuition"];
        }
        
        private void InitClass() {
            this.DataSetName = "DatasetHerder";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DatasetHerder.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableHerder = new HerderDataTable();
            this.Tables.Add(this.tableHerder);
            this.tableHerderTuition = new HerderTuitionDataTable();
            this.Tables.Add(this.tableHerderTuition);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("HerderHerderTuition", new DataColumn[] {
                        this.tableHerder.idColumn}, new DataColumn[] {
                        this.tableHerderTuition.stidColumn});
            this.tableHerderTuition.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            this.relationHerderHerderTuition = new DataRelation("HerderHerderTuition", new DataColumn[] {
                        this.tableHerder.idColumn}, new DataColumn[] {
                        this.tableHerderTuition.stidColumn}, false);
            this.Relations.Add(this.relationHerderHerderTuition);
        }
        
        private bool ShouldSerializeHerder() {
            return false;
        }
        
        private bool ShouldSerializeHerderTuition() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void HerderRowChangeEventHandler(object sender, HerderRowChangeEvent e);
        
        public delegate void HerderTuitionRowChangeEventHandler(object sender, HerderTuitionRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HerderDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnid;
            
            private DataColumn columnlname;
            
            private DataColumn columnfname;
            
            private DataColumn columngender;
            
            private DataColumn columnprof;
            
            private DataColumn columngrade;
            
            private DataColumn columngpa;
            
            private DataColumn columnregion;
            
            private DataColumn columnadmisno;
            
            private DataColumn columnpasno;
            
            private DataColumn columnregno;
            
            private DataColumn columnpa_regno;
            
            private DataColumn columnma_regno;
            
            private DataColumn columnherds;
            
            private DataColumn columnstate;
            
            private DataColumn columnnote;
            
            internal HerderDataTable() : 
                    base("Herder") {
                this.InitClass();
            }
            
            internal HerderDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            internal DataColumn lnameColumn {
                get {
                    return this.columnlname;
                }
            }
            
            internal DataColumn fnameColumn {
                get {
                    return this.columnfname;
                }
            }
            
            internal DataColumn genderColumn {
                get {
                    return this.columngender;
                }
            }
            
            internal DataColumn profColumn {
                get {
                    return this.columnprof;
                }
            }
            
            internal DataColumn gradeColumn {
                get {
                    return this.columngrade;
                }
            }
            
            internal DataColumn gpaColumn {
                get {
                    return this.columngpa;
                }
            }
            
            internal DataColumn regionColumn {
                get {
                    return this.columnregion;
                }
            }
            
            internal DataColumn admisnoColumn {
                get {
                    return this.columnadmisno;
                }
            }
            
            internal DataColumn pasnoColumn {
                get {
                    return this.columnpasno;
                }
            }
            
            internal DataColumn regnoColumn {
                get {
                    return this.columnregno;
                }
            }
            
            internal DataColumn pa_regnoColumn {
                get {
                    return this.columnpa_regno;
                }
            }
            
            internal DataColumn ma_regnoColumn {
                get {
                    return this.columnma_regno;
                }
            }
            
            internal DataColumn herdsColumn {
                get {
                    return this.columnherds;
                }
            }
            
            internal DataColumn stateColumn {
                get {
                    return this.columnstate;
                }
            }
            
            internal DataColumn noteColumn {
                get {
                    return this.columnnote;
                }
            }
            
            public HerderRow this[int index] {
                get {
                    return ((HerderRow)(this.Rows[index]));
                }
            }
            
            public event HerderRowChangeEventHandler HerderRowChanged;
            
            public event HerderRowChangeEventHandler HerderRowChanging;
            
            public event HerderRowChangeEventHandler HerderRowDeleted;
            
            public event HerderRowChangeEventHandler HerderRowDeleting;
            
            public void AddHerderRow(HerderRow row) {
                this.Rows.Add(row);
            }
            
            public HerderRow AddHerderRow(string lname, string fname, string gender, string prof, System.Byte grade, System.Single gpa, string region, string admisno, string pasno, string regno, string pa_regno, string ma_regno, short herds, System.Byte state, string note) {
                HerderRow rowHerderRow = ((HerderRow)(this.NewRow()));
                rowHerderRow.ItemArray = new object[] {
                        null,
                        lname,
                        fname,
                        gender,
                        prof,
                        grade,
                        gpa,
                        region,
                        admisno,
                        pasno,
                        regno,
                        pa_regno,
                        ma_regno,
                        herds,
                        state,
                        note};
                this.Rows.Add(rowHerderRow);
                return rowHerderRow;
            }
            
            public HerderRow FindByid(int id) {
                return ((HerderRow)(this.Rows.Find(new object[] {
                            id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                HerderDataTable cln = ((HerderDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new HerderDataTable();
            }
            
            internal void InitVars() {
                this.columnid = this.Columns["id"];
                this.columnlname = this.Columns["lname"];
                this.columnfname = this.Columns["fname"];
                this.columngender = this.Columns["gender"];
                this.columnprof = this.Columns["prof"];
                this.columngrade = this.Columns["grade"];
                this.columngpa = this.Columns["gpa"];
                this.columnregion = this.Columns["region"];
                this.columnadmisno = this.Columns["admisno"];
                this.columnpasno = this.Columns["pasno"];
                this.columnregno = this.Columns["regno"];
                this.columnpa_regno = this.Columns["pa_regno"];
                this.columnma_regno = this.Columns["ma_regno"];
                this.columnherds = this.Columns["herds"];
                this.columnstate = this.Columns["state"];
                this.columnnote = this.Columns["note"];
            }
            
            private void InitClass() {
                this.columnid = new DataColumn("id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnid);
                this.columnlname = new DataColumn("lname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlname);
                this.columnfname = new DataColumn("fname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnfname);
                this.columngender = new DataColumn("gender", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngender);
                this.columnprof = new DataColumn("prof", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnprof);
                this.columngrade = new DataColumn("grade", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngrade);
                this.columngpa = new DataColumn("gpa", typeof(System.Single), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngpa);
                this.columnregion = new DataColumn("region", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnregion);
                this.columnadmisno = new DataColumn("admisno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnadmisno);
                this.columnpasno = new DataColumn("pasno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpasno);
                this.columnregno = new DataColumn("regno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnregno);
                this.columnpa_regno = new DataColumn("pa_regno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpa_regno);
                this.columnma_regno = new DataColumn("ma_regno", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnma_regno);
                this.columnherds = new DataColumn("herds", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnherds);
                this.columnstate = new DataColumn("state", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstate);
                this.columnnote = new DataColumn("note", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnote);
                this.Constraints.Add(new UniqueConstraint("DatasetHerderKey1", new DataColumn[] {
                                this.columnid}, true));
                this.columnid.AutoIncrement = true;
                this.columnid.AllowDBNull = false;
                this.columnid.Unique = true;
                this.columngender.DefaultValue = "эр";
                this.columngrade.DefaultValue = 1;
                this.columngpa.DefaultValue = 0F;
                this.columnregion.DefaultValue = "Улаанбаатар";
                this.columnherds.DefaultValue = 0;
                this.columnstate.DefaultValue = 1;
            }
            
            public HerderRow NewHerderRow() {
                return ((HerderRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new HerderRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(HerderRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.HerderRowChanged != null)) {
                    this.HerderRowChanged(this, new HerderRowChangeEvent(((HerderRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.HerderRowChanging != null)) {
                    this.HerderRowChanging(this, new HerderRowChangeEvent(((HerderRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.HerderRowDeleted != null)) {
                    this.HerderRowDeleted(this, new HerderRowChangeEvent(((HerderRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.HerderRowDeleting != null)) {
                    this.HerderRowDeleting(this, new HerderRowChangeEvent(((HerderRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveHerderRow(HerderRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HerderRow : DataRow {
            
            private HerderDataTable tableHerder;
            
            internal HerderRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableHerder = ((HerderDataTable)(this.Table));
            }
            
            public int id {
                get {
                    return ((int)(this[this.tableHerder.idColumn]));
                }
                set {
                    this[this.tableHerder.idColumn] = value;
                }
            }
            
            public string lname {
                get {
                    try {
                        return ((string)(this[this.tableHerder.lnameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.lnameColumn] = value;
                }
            }
            
            public string fname {
                get {
                    try {
                        return ((string)(this[this.tableHerder.fnameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.fnameColumn] = value;
                }
            }
            
            public string gender {
                get {
                    try {
                        return ((string)(this[this.tableHerder.genderColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.genderColumn] = value;
                }
            }
            
            public string prof {
                get {
                    try {
                        return ((string)(this[this.tableHerder.profColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.profColumn] = value;
                }
            }
            
            public System.Byte grade {
                get {
                    try {
                        return ((System.Byte)(this[this.tableHerder.gradeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.gradeColumn] = value;
                }
            }
            
            public System.Single gpa {
                get {
                    try {
                        return ((System.Single)(this[this.tableHerder.gpaColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.gpaColumn] = value;
                }
            }
            
            public string region {
                get {
                    try {
                        return ((string)(this[this.tableHerder.regionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.regionColumn] = value;
                }
            }
            
            public string admisno {
                get {
                    try {
                        return ((string)(this[this.tableHerder.admisnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.admisnoColumn] = value;
                }
            }
            
            public string pasno {
                get {
                    try {
                        return ((string)(this[this.tableHerder.pasnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.pasnoColumn] = value;
                }
            }
            
            public string regno {
                get {
                    try {
                        return ((string)(this[this.tableHerder.regnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.regnoColumn] = value;
                }
            }
            
            public string pa_regno {
                get {
                    try {
                        return ((string)(this[this.tableHerder.pa_regnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.pa_regnoColumn] = value;
                }
            }
            
            public string ma_regno {
                get {
                    try {
                        return ((string)(this[this.tableHerder.ma_regnoColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.ma_regnoColumn] = value;
                }
            }
            
            public short herds {
                get {
                    try {
                        return ((short)(this[this.tableHerder.herdsColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.herdsColumn] = value;
                }
            }
            
            public System.Byte state {
                get {
                    try {
                        return ((System.Byte)(this[this.tableHerder.stateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.stateColumn] = value;
                }
            }
            
            public string note {
                get {
                    try {
                        return ((string)(this[this.tableHerder.noteColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerder.noteColumn] = value;
                }
            }
            
            public bool IslnameNull() {
                return this.IsNull(this.tableHerder.lnameColumn);
            }
            
            public void SetlnameNull() {
                this[this.tableHerder.lnameColumn] = System.Convert.DBNull;
            }
            
            public bool IsfnameNull() {
                return this.IsNull(this.tableHerder.fnameColumn);
            }
            
            public void SetfnameNull() {
                this[this.tableHerder.fnameColumn] = System.Convert.DBNull;
            }
            
            public bool IsgenderNull() {
                return this.IsNull(this.tableHerder.genderColumn);
            }
            
            public void SetgenderNull() {
                this[this.tableHerder.genderColumn] = System.Convert.DBNull;
            }
            
            public bool IsprofNull() {
                return this.IsNull(this.tableHerder.profColumn);
            }
            
            public void SetprofNull() {
                this[this.tableHerder.profColumn] = System.Convert.DBNull;
            }
            
            public bool IsgradeNull() {
                return this.IsNull(this.tableHerder.gradeColumn);
            }
            
            public void SetgradeNull() {
                this[this.tableHerder.gradeColumn] = System.Convert.DBNull;
            }
            
            public bool IsgpaNull() {
                return this.IsNull(this.tableHerder.gpaColumn);
            }
            
            public void SetgpaNull() {
                this[this.tableHerder.gpaColumn] = System.Convert.DBNull;
            }
            
            public bool IsregionNull() {
                return this.IsNull(this.tableHerder.regionColumn);
            }
            
            public void SetregionNull() {
                this[this.tableHerder.regionColumn] = System.Convert.DBNull;
            }
            
            public bool IsadmisnoNull() {
                return this.IsNull(this.tableHerder.admisnoColumn);
            }
            
            public void SetadmisnoNull() {
                this[this.tableHerder.admisnoColumn] = System.Convert.DBNull;
            }
            
            public bool IspasnoNull() {
                return this.IsNull(this.tableHerder.pasnoColumn);
            }
            
            public void SetpasnoNull() {
                this[this.tableHerder.pasnoColumn] = System.Convert.DBNull;
            }
            
            public bool IsregnoNull() {
                return this.IsNull(this.tableHerder.regnoColumn);
            }
            
            public void SetregnoNull() {
                this[this.tableHerder.regnoColumn] = System.Convert.DBNull;
            }
            
            public bool Ispa_regnoNull() {
                return this.IsNull(this.tableHerder.pa_regnoColumn);
            }
            
            public void Setpa_regnoNull() {
                this[this.tableHerder.pa_regnoColumn] = System.Convert.DBNull;
            }
            
            public bool Isma_regnoNull() {
                return this.IsNull(this.tableHerder.ma_regnoColumn);
            }
            
            public void Setma_regnoNull() {
                this[this.tableHerder.ma_regnoColumn] = System.Convert.DBNull;
            }
            
            public bool IsherdsNull() {
                return this.IsNull(this.tableHerder.herdsColumn);
            }
            
            public void SetherdsNull() {
                this[this.tableHerder.herdsColumn] = System.Convert.DBNull;
            }
            
            public bool IsstateNull() {
                return this.IsNull(this.tableHerder.stateColumn);
            }
            
            public void SetstateNull() {
                this[this.tableHerder.stateColumn] = System.Convert.DBNull;
            }
            
            public bool IsnoteNull() {
                return this.IsNull(this.tableHerder.noteColumn);
            }
            
            public void SetnoteNull() {
                this[this.tableHerder.noteColumn] = System.Convert.DBNull;
            }
            
            public HerderTuitionRow[] GetHerderTuitionRows() {
                return ((HerderTuitionRow[])(this.GetChildRows(this.Table.ChildRelations["HerderHerderTuition"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HerderRowChangeEvent : EventArgs {
            
            private HerderRow eventRow;
            
            private DataRowAction eventAction;
            
            public HerderRowChangeEvent(HerderRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public HerderRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HerderTuitionDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnstid;
            
            private DataColumn columntdate;
            
            private DataColumn columntsize;
            
            private DataColumn columntdesc;
            
            internal HerderTuitionDataTable() : 
                    base("HerderTuition") {
                this.InitClass();
            }
            
            internal HerderTuitionDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn stidColumn {
                get {
                    return this.columnstid;
                }
            }
            
            internal DataColumn tdateColumn {
                get {
                    return this.columntdate;
                }
            }
            
            internal DataColumn tsizeColumn {
                get {
                    return this.columntsize;
                }
            }
            
            internal DataColumn tdescColumn {
                get {
                    return this.columntdesc;
                }
            }
            
            public HerderTuitionRow this[int index] {
                get {
                    return ((HerderTuitionRow)(this.Rows[index]));
                }
            }
            
            public event HerderTuitionRowChangeEventHandler HerderTuitionRowChanged;
            
            public event HerderTuitionRowChangeEventHandler HerderTuitionRowChanging;
            
            public event HerderTuitionRowChangeEventHandler HerderTuitionRowDeleted;
            
            public event HerderTuitionRowChangeEventHandler HerderTuitionRowDeleting;
            
            public void AddHerderTuitionRow(HerderTuitionRow row) {
                this.Rows.Add(row);
            }
            
            public HerderTuitionRow AddHerderTuitionRow(HerderRow parentHerderRowByHerderHerderTuition, System.DateTime tdate, System.Single tsize, string tdesc) {
                HerderTuitionRow rowHerderTuitionRow = ((HerderTuitionRow)(this.NewRow()));
                rowHerderTuitionRow.ItemArray = new object[] {
                        parentHerderRowByHerderHerderTuition[0],
                        tdate,
                        tsize,
                        tdesc};
                this.Rows.Add(rowHerderTuitionRow);
                return rowHerderTuitionRow;
            }
            
            public HerderTuitionRow FindBystidtdate(int stid, System.DateTime tdate) {
                return ((HerderTuitionRow)(this.Rows.Find(new object[] {
                            stid,
                            tdate})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                HerderTuitionDataTable cln = ((HerderTuitionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new HerderTuitionDataTable();
            }
            
            internal void InitVars() {
                this.columnstid = this.Columns["stid"];
                this.columntdate = this.Columns["tdate"];
                this.columntsize = this.Columns["tsize"];
                this.columntdesc = this.Columns["tdesc"];
            }
            
            private void InitClass() {
                this.columnstid = new DataColumn("stid", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstid);
                this.columntdate = new DataColumn("tdate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntdate);
                this.columntsize = new DataColumn("tsize", typeof(System.Single), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntsize);
                this.columntdesc = new DataColumn("tdesc", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columntdesc);
                this.Constraints.Add(new UniqueConstraint("DatasetHerderKey2", new DataColumn[] {
                                this.columnstid,
                                this.columntdate}, true));
                this.Constraints.Add(new UniqueConstraint("key1", new DataColumn[] {
                                this.columnstid}, false));
                this.columnstid.AllowDBNull = false;
                this.columnstid.Unique = true;
                this.columntdate.AllowDBNull = false;
            }
            
            public HerderTuitionRow NewHerderTuitionRow() {
                return ((HerderTuitionRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new HerderTuitionRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(HerderTuitionRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.HerderTuitionRowChanged != null)) {
                    this.HerderTuitionRowChanged(this, new HerderTuitionRowChangeEvent(((HerderTuitionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.HerderTuitionRowChanging != null)) {
                    this.HerderTuitionRowChanging(this, new HerderTuitionRowChangeEvent(((HerderTuitionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.HerderTuitionRowDeleted != null)) {
                    this.HerderTuitionRowDeleted(this, new HerderTuitionRowChangeEvent(((HerderTuitionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.HerderTuitionRowDeleting != null)) {
                    this.HerderTuitionRowDeleting(this, new HerderTuitionRowChangeEvent(((HerderTuitionRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveHerderTuitionRow(HerderTuitionRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HerderTuitionRow : DataRow {
            
            private HerderTuitionDataTable tableHerderTuition;
            
            internal HerderTuitionRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableHerderTuition = ((HerderTuitionDataTable)(this.Table));
            }
            
            public int stid {
                get {
                    return ((int)(this[this.tableHerderTuition.stidColumn]));
                }
                set {
                    this[this.tableHerderTuition.stidColumn] = value;
                }
            }
            
            public System.DateTime tdate {
                get {
                    return ((System.DateTime)(this[this.tableHerderTuition.tdateColumn]));
                }
                set {
                    this[this.tableHerderTuition.tdateColumn] = value;
                }
            }
            
            public System.Single tsize {
                get {
                    try {
                        return ((System.Single)(this[this.tableHerderTuition.tsizeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerderTuition.tsizeColumn] = value;
                }
            }
            
            public string tdesc {
                get {
                    try {
                        return ((string)(this[this.tableHerderTuition.tdescColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableHerderTuition.tdescColumn] = value;
                }
            }
            
            public HerderRow HerderRow {
                get {
                    return ((HerderRow)(this.GetParentRow(this.Table.ParentRelations["HerderHerderTuition"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["HerderHerderTuition"]);
                }
            }
            
            public bool IstsizeNull() {
                return this.IsNull(this.tableHerderTuition.tsizeColumn);
            }
            
            public void SettsizeNull() {
                this[this.tableHerderTuition.tsizeColumn] = System.Convert.DBNull;
            }
            
            public bool IstdescNull() {
                return this.IsNull(this.tableHerderTuition.tdescColumn);
            }
            
            public void SettdescNull() {
                this[this.tableHerderTuition.tdescColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class HerderTuitionRowChangeEvent : EventArgs {
            
            private HerderTuitionRow eventRow;
            
            private DataRowAction eventAction;
            
            public HerderTuitionRowChangeEvent(HerderTuitionRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public HerderTuitionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
